language: python
sudo: false
os:
  - linux
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
env:
  - NUMPY=1.14 NUMBA=0.46
  - NUMPY=1.14 NUMBA=0.47
  - NUMPY=1.15 NUMBA=0.46
  - NUMPY=1.15 NUMBA=0.47
  - NUMPY=1.16 NUMBA=0.46
  - NUMPY=1.16 NUMBA=0.47
  - NUMPY=1.17 NUMBA=0.46
  - NUMPY=1.17 NUMBA=0.47
  - NUMPY=1.17 NUMBA=0.48
  - NUMPY=1.18 NUMBA=0.47
  - NUMPY=1.18 NUMBA=0.48
install:
  - pip install -e .[ci_test,doc]
  - pip install numpy==$NUMPY
  - pip install numba==$NUMBA
script:
  - pytest
  - sphinx-build docs/source docs/build #-W
after_success:
    - codecov
